name: Build React App
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm Install
        run: |
          npm install
      - name: Env 파일 추가
        run: |
          echo "REACT_APP_AWS_S3_BUCKET_REGION=$REACT_APP_AWS_S3_BUCKET_REGION" >> .env
          echo "REACT_APP_AWS_S3_BUCKET_ACCESS_KEY_ID=$REACT_APP_AWS_S3_BUCKET_ACCESS_KEY_ID" >> .env
          echo "REACT_APP_AWS_S3_BUCKET_SECRET_ACCESS_KEY=$REACT_APP_AWS_S3_BUCKET_SECRET_ACCESS_KEY" >> .env
        env:
          REACT_APP_AWS_S3_BUCKET_REGION: ${{ secrets.REACT_APP_AWS_S3_BUCKET_REGION }}
          REACT_APP_AWS_S3_BUCKET_ACCESS_KEY_ID: ${{ secrets.REACT_APP_AWS_S3_BUCKET_ACCESS_KEY_ID }}
          REACT_APP_AWS_S3_BUCKET_SECRET_ACCESS_KEY: ${{ secrets.REACT_APP_AWS_S3_BUCKET_SECRET_ACCESS_KEY }}
      - name: Npm Build
        continue-on-error: true
        run: |
          npm run build
      - name: Npm Postbuild
        run: |
          npm run postbuild
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 sync ./build s3://${{secrets.AWS_S3_BUCKET}}
